---

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group }}"
    allocation_method: Static
    name: "{{ azure_vm_name }}PublicIP"
  register: output_ip_address

- name: Dump public IP for VM which will be created
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}."

- name: Create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_name }}Nic"
    virtual_network: "{{ azure_vnet_name }}"
    subnet: "{{ azure_subnet_name }}"
    public_ip_name: "{{ azure_vm_name }}PublicIP"
    security_group: "{{ azure_security_group }}"

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_name }}"
    vm_size: "{{ azure_vm_size }}"
    admin_username: "{{ azure_admin }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ azure_admin }}/.ssh/authorized_keys
        key_data: "{{ public_key }}"
    network_interfaces: "{{ azure_vm_name }}Nic"
    tags:
      env: "{{ azure_tag }}"
    image:
      offer: RHEL
      publisher: RedHat
      sku: '8.0'
      version: latest
