---
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ azure_resource_group }}"
    location: "{{ azure_location }}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vnet_name }}"
    address_prefixes: "{{ azure_subnet_range }}"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_subnet_name }}"
    address_prefix: "{{ azure_subnet_mask }}"
    virtual_network: "{{ azure_vnet_name }}"

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group }}"
    allocation_method: Static
    name: "{{ azure_public_ip_name }}"
  register: output_ip_address

- name: Dump public IP for VM which will be created
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}."

- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_security_group }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound

- name: Create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_nic_name }}"
    virtual_network: "{{ azure_vnet_name }}"
    subnet: "{{ azure_subnet_name }}"
    public_ip_name: "{{ azure_public_ip_name }}"
    security_group: "{{ azure_security_group }}"
