---
- name: Remove a VM and all resources that were autocreated
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_name }}"
    remove_on_absent: all_autocreated
    state: absent

- name: Delete network interface
  azure_rm_networkinterface:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_name }}Nic"
    state: absent

- name: Delete public ip
  azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_name }}PublicIP"
    state: absent
