---
- name: Create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_name }}Nic"
    virtual_network: "{{ azure_vnet_name }}"
    subnet: "{{ azure_subnet_name }}"
    public_ip_name: "{{ azure_vm_name }}PublicIP"
    security_group: "{{ azure_security_group }}"

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_name }}"
    vm_size: "{{ azure_vm_size }}"
    admin_username: "{{ azure_admin }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ azure_admin }}/.ssh/authorized_keys
        key_data: "{{ public_key }}"
    network_interfaces: "{{ azure_vm_name }}Nic"
    tags:
      env: "{{ azure_tag }}"
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.5'
      version: latest
