---
- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_name }}"
    vm_size: "{{ azure_vm_size }}"
    admin_username: "{{ azure_admin }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ azure_admin }}/.ssh/authorized_keys
        key_data: "{{ public_key }}"
    network_interfaces: "{{ azure_nic_name }}"
    tag:
      env: {{ azure_tag }}
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.5'
      version: latest
