---
- name: Install NodeJS packages
  yum:
    name:
      - npm
      - nodejs
      - git
    state: present

- name: Install globally required npm packages 
  npm:
    name: pm2
    state: present
    global: yes

- name: Install globally required npm packages 
  npm:
    name: babel-cli
    ignore_scripts: yes
    state: present
    global: yes

- name: Clone web app git repo to location
  git:
    repo: '{{ gitRepo }}'
    dest: '{{ deploymentPath }}'
    force: yes

- name: Install node dependencies
  command: npm install
  args:
    chdir: '{{ deploymentPath }}'

- name: Build node binaries
  command: npm run-script build
  args:
    chdir: '{{ deploymentPath }}'

- name: Stop pm2 managed app
  shell: pm2 stop all
  ignore_errors: True
  args:
    chdir: '{{ deploymentPath }}'
  register: pm2stop
  failed_when: pm2stop.rc != 0

- name: Delete previous runs
  shell: pm2 delete index
  ignore_errors: True
  args:
    chdir: '{{ deploymentPath }}'
  register: pm2delete
  failed_when: pm2delete.rc != 0

- name: Start pm2 managed app
  shell: " DB_HOST='{{ db_host }}' DB_USER='{{ db_user}}' DB_PASS='{{db_pass}}' DB_DB='{{db_db}}' pm2 start ./index.js"
  args:
    chdir: '{{ deploymentPath }}/build'

- debug:
    msg: " DB_HOST='{{ db_host }}' DB_USER='{{ db_user}}' DB_PASS='{{db_pass}}' DB_DB='{{db_db}}' "
