---
- name: Create a MySQL instance in GCP
  gcp_sql_instance:
    name: "{{ db_db }}"
    settings:
      ip_configuration:
        authorized_networks:
        - name: interweb
          value: 0.0.0.0/0
      tier: db-n1-standard-1
    region: us-central1
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file }}"
    state: present
    database_version: MYSQL_5_7
  register: instance

- name: create a user
  gcp_sql_user:
    name: "{{ db_user}}"
    password: "{{ db_pass }}"
    instance: "{{ instance }}"
    project: "{{ gcp_project }}"
    host: "%"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: create a database
  gcp_sql_database:
    name: "{{ db_db }}"
    charset: utf8
    instance: "{{ instance }}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- set_fact:
    db_host: "{{item.ipAddress}}"
  with_items: "{{ instance.ipAddresses }}"
  when: "{{ item.type == 'PRIMARY' }}"

- set_stats:
    data: 
      db_host: "{{ db_host }}"

- debug: 
    msg: "{{db_host}}"