---
- name: Create a database in GCP
  gcp_sql_instance:
    name: "{{ db_db }}"
    settings:
      ip_configuration:
        authorized_networks:
        - name: interweb
          value: 0.0.0.0/0
      tier: "{{ db_info[db_type].tier }}"
    region: "{{ gcp_region }}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file }}"
    state: "{{ db_state }}"
    database_version: "{{ db_info[db_type].database_version }}"
    backend_type: "{{ db_info[db_type].backend_type }}"
  register: instance
    
- set_fact:
    db_host: "{{item.ipAddress}}"
  with_items: "{{ instance.ipAddresses }}"
  when: "{{ item.type == 'PRIMARY' }}"

- set_stats:
    data: 
      db_host: "{{ db_host }}"
      instance: "{{ instance }}"
      # db_user: "{{ db_user }}"
      # db_pass: "{{ db_pass }}"

- debug: 
    msg: 
      - "You passed additional verbosity flags, so you must be troubleshooting. Here's some info:"
      - "Instance: {{instance}}"
      # - "Username: {{db_user}}"
      # - "Password: {{db_pass}}"
    verbosity: 2