---
- name: Create a database in GCP
  gcp_sql_instance:
    name: "{{ db_db }}"
    settings:
      ip_configuration:
        authorized_networks:
        - name: interweb
          value: 0.0.0.0/0
      tier: "{{ db_info[db_type].tier }}"
    region: us-central1
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file }}"
    state: "{{ db_state }}"
    database_version: MYSQL_5_7
    backend_type: "{{ db_info[db_type].backend_type }}"
  register: instance
    
- name: Bring in config tasks
  include_tasks: config.yml
  when: db_state == 'present'