---
- name: Disable firewalld for now
  service: 
    name: firewalld
    state: stopped
    enabled: no

- name: Install NodeJS and HTTPD packages
  yum:
    name:
      - npm
      - nodejs
      - httpd
      - git
    state: present

- name: Clone web app git repo to location
  git:
    repo: https://github.com/kyleabenson/frontendDemo.git
    dest: /home/ec2-user/frontendDemo
    force: yes

- name: Install node dependencies
  command: npm install
  args:
    chdir: /home/ec2-user/frontendDemo

- name: Build production binaries with temporary hardcoded express url
  shell: "REACT_APP_EXPRESS_URL=http://{{ express_server }} npm run build"
  args:
    chdir: /home/ec2-user/frontendDemo

- name: Move build server to html directory
  copy:
    remote_src: true
    src: /home/ec2-user/frontendDemo/build/
    dest: /var/www/html/
    owner: apache
    group: apache
    force: yes
  notify: 
    - restart httpd

- name: Start apache service
  service:
    name: httpd
    state: started
    enabled: yes
  