---
- name: Install pip packages needed
  pip:
    name: firewalld

- name: Disable SELinux
  selinux:
    policy: targeted
    state: permissive

- firewalld:
    service: http
    permanent: yes
    state: enabled

- firewalld:
    port: 5000/tcp
    permanent: yes
    state: disabled
