---
- name: CREATE ORGANIZATIONS
  include_tasks: rbac_orgs.yml

- name: CREATE TEAMS
  include_tasks: rbac_teams.yml

- name: CREATE USERS
  include_tasks: rbac_users.yml

- name: MODIFY USER MEMBERSHIPS
  include_tasks: rbac_users_memberships.yml